version: '3'
services:
  npx:
    image: node:16.18
    container_name: school-web-security
    user: node
    command: npx serve
    volumes:
      - .:/sources
    working_dir: /sources
    ports:
      - 3000:3000
